name: "adguard"
services:
  adguard:
    image: "11notes/adguard:0.107.59"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "etc:/adguard/etc"
      - "var:/adguard/var"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8443:8443/tcp"
    networks:
      frontend:
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 53
    restart: "always"

volumes:
  etc:
  var:

networks:
  frontend: